import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

// Import Outfit font
const outfit = Outfit({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(outfit.className, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
