export const players = [
    {
    name: "Cristiano Ronaldo",
    stat: 93,
    image: "./js/ronaldo.png",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/2560px-Flag_of_Portugal.svg.png",
    club: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Nassr_FC_Logo.svg/1200px-Nassr_FC_Logo.svg.png",
    position: "CF",
    pac: 86,
    sho: 95,
    pas: 88,
    dri: 92,
    def: 40,
    phy: 68,
  },
  {
    name: "Kylian Mbappé",
    stat: 92,
    image: "./js/Mbappe.png",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/2560px-Flag_of_France.svg.png",
    club: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    position: "ST",
    pac: 97,
    sho: 90,
    pas: 80,
    dri: 93,
    def: 36,
    phy: 78,
  },
  {
    name: "Lionel Messi",
    stat: 93,
    image: "./js/messi.png",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/2560px-Flag_of_Argentina.svg.png",
    club: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Inter_Miami_CF_logo.svg/1200px-Inter_Miami_CF_logo.svg.png",
    position: "RW",
    pac: 85,
    sho: 92,
    pas: 91,
    dri: 94,
    def: 38,
    phy: 65,
  },
  {
    name: "Erling Haaland",
    stat: 91,
    flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    club: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    position: "ST",
    pac: 89,
    sho: 94,
    pas: 70,
    dri: 80,
    def: 45,
    phy: 88,
  },
  {
    name: "Kevin De Bruyne",
    stat: 91,
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/2560px-Flag_of_Belgium_%28civil%29.svg.png",
    club: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    position: "CM",
    pac: 74,
    sho: 86,
    pas: 93,
    dri: 88,
    def: 64,
    phy: 78,
  },
  {
    name: "Virgil van Dijk",
    stat: 90,
    flag: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
    club: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
    position: "CB",
    pac: 78,
    sho: 60,
    pas: 71,
    dri: 72,
    def: 91,
    phy: 86,
  },
  {
    name: "Jude Bellingham",
    stat: 88,
    flag: "https://upload.wikimedia.org/wikipedia/en/b/be/Flag_of_England.svg",
    club: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    position: "CM",
    pac: 79,
    sho: 82,
    pas: 84,
    dri: 87,
    def: 76,
    phy: 82,
  },
  {
    name: "Vinícius Jr.",
    stat: 89,
    flag: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
    club: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    position: "LW",
    pac: 95,
    sho: 83,
    pas: 78,
    dri: 92,
    def: 29,
    phy: 66,
  }
];
